### PR TITLE
R5 ready

### PR DESCRIPTION
**Pull request by krosk93**
Changed pom (wrong repos, didn't download the dependencies) <- Is it public?
Updated Configuration <- Using new FileConfiguration
Replaced EndermanPickupEvent <- Replaced with EntityChangeBlockEvent

### CODE REVIEW

**Comment by md-5** [comment]
Seems good

**Comment by NolanSyKinsley** [comment]
I was exited to see this, but when I try to compile it I am given this error,

[ERROR] /home/paco/Compiling/Acampadas21-Deadbolt-e281af7/src/main/java/com/daemitus/deadbolt/listener/DeadboltListener.java:[18,7] com.daemitus.deadbolt.listener.DeadboltListener is not abstract and does not override abstract method canEndermanPickup(com.daemitus.deadbolt.Deadbolted,org.bukkit.event.entity.EntityChangeBlockEvent) in com.daemitus.deadbolt.listener.ListenerInterface
[ERROR] /home/paco/Compiling/Acampadas21-Deadbolt-e281af7/src/main/java/com/daemitus/deadbolt/listener/DeadboltListener.java:[39,4] method does not override or implement a method from a supertype

**Comment by krosk93** [comment]
Yes, forgot to change EndermanPickupEvent on that class, I have just noticed it too. Making another pull request now.

**Comment by krosk93** [comment]
Pull request done: #48

**Comment by NolanSyKinsley** [comment]
OH! the repo, its not "http://guardian.mossycobble.com:8080/repo/content/groups/public/" it is "http://guardian.mossycobble.com:8080/nexus/content/groups/public/" 

also, pex 1.19 is not in the repo, needs to stay 1.18 till it updates

**Comment by krosk93** [comment]
I did not change this repo, that was in Deadbolt's source when I fetched it. As it was not working, I added bukkit's official, one that has many bukkit plugins, and mine. And PEX is in my repo, look: http://acampadas21.net:8026/nexus-2.0/content/groups/public/. Maybe the repo info wasn't updated. Please do a "mvn clean install" now, if it still doesn't work, tell me. It compiles since #48 fix.

**Comment by NolanSyKinsley** [comment]
ahh, I see. I knew you didnt change it,You were going to be submitting another pull request and I was trying to tell you before you did so it could be included. 

I did not see you had added a repo with it in there, I stand corrected. Thank you for these pull requests, they finally let me compile it so I can fix a couple of things for my server.

**Pull request merged**
