### PR TITLE
Remove support for left click.

### PR DESCRIPTION
**Pull request by Phreyr**
This corresponds with normal behavior now.

### CODE REVIEW

**Comment by md-5** [comment]
So doors don't open on left click in Vanilla?

**Comment by Phreyr** [comment]
Correct.

**Comment by Phreyr** [comment]
Not since last year.

https://mojang.com/2012/10/minecraft-snapshot-12w40a/

**Comment by Brianetta** [comment]
Is there still a way to correct a door that's locked in the wrong position? If a deadbolted door has a timer, is opened, and then the chunk is unloaded (for example, the player teleports away) before the time elapses, the door will remain locked open. A left click by the owner would remedy this.

**Pull request merged**
