### PR TITLE
Added an optional auto-expire feature and fixed an R5 issue.

### PR DESCRIPTION
**Pull request by oloflarsson**

### CODE REVIEW

**Comment by md-5** [comment]
Nom, nom nom. Ill take a proper look

**Comment by oloflarsson** [comment]
This plugin will replace lockette totally if we improve it a bit. I have quiet a lot of ideas on how to do that actually and I am using this plugin on my own server :) I will pull request all the stuff I make.

**Comment by md-5** [comment]
Our original goal, havent heard from @daemitus  for a bit

**Comment by daemitus** [comment]
@md-5
@oloflarsson 
Call it a combination of apathy, qualifying for the Mid-Atlantic Cyberdefense regionals, and deploying in nearly 4 weeks. Ive had alot on my plate for months now.

**Comment by oloflarsson** [comment]
It is all ok if you have lots to do :) It is open source. So I anyone need more features or would like the plugin to be better... we can just contribute ^^

**Pull request merged**
